baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '王宇萌'
theme = "nostyleplease"
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            # allows rendering of raw html in markup files, kinda dangerous
            unsafe = true   
